# Advanced Pandas Masterclass (MultiIndex, Window Functions, Time Series)

**Topics Covered:**
- MultiIndexing and Hierarchical Indexing
- Window Functions (`rolling`, `expanding`)
- Time Series Handling in Pandas
- Resampling, Shifting, and Date Ranges
- Performance Tips
- Interview-Level Coding Questions & Answers

In [1]:
# 📦 Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
import glob

## 🔁 MultiIndexing and Hierarchical Indexing

In [3]:
# Create a sample dataset
arrays = [
    ['Math', 'Math', 'Science', 'Science'],
    ['Test1', 'Test2', 'Test1', 'Test2']
]
index = pd.MultiIndex.from_arrays(arrays, names=('Subject', 'Test'))
df = pd.DataFrame({'Score': [88, 92, 85, 90]}, index=index)
df

               Score
Subject Test
Math    Test1     88
        Test2     92
Science Test1     85
        Test2     90

### 🧠 Interview Question:
**Q: How would you access all `Test1` scores?**
**A:** `df.xs('Test1', level='Test')`

## 📈 Window Functions: Rolling & Expanding

In [8]:
# Create a simple time-series-like data
np.random.seed(42)
data = pd.Series(np.random.randint(20, 100, size=10))
data.rolling(window=3).mean()

0          NaN
1          NaN
2    65.333333
3    68.333333
4    70.333333
5    71.333333
6    76.000000
7    77.000000
8    53.000000
9    35.333333
dtype: float64

**Expanding window:** Useful for cumulative statistics

In [11]:
data.expanding().mean()

0    71.000000
1    52.500000
2    65.333333
3    69.000000
4    63.200000
5    68.333333
6    72.000000
7    68.375000
8    63.222222
9    61.000000
dtype: float64

## ⏳ Time Series with Pandas

In [14]:
# Create a time-indexed DataFrame
date_rng = pd.date_range(start='2023-01-01', end='2023-01-10', freq='D')
ts_df = pd.DataFrame(date_rng, columns=['date'])
ts_df['value'] = np.random.randint(10, 100, size=(len(date_rng)))
ts_df = ts_df.set_index('date')
ts_df.head()

            value
date
2023-01-01     62
2023-01-02     11
2023-01-03     97
2023-01-04     39
2023-01-05     47

### 📦 Resampling
`resample('2D')` means 2-day frequency

In [17]:
ts_df.resample('2D').mean()

            value
date
2023-01-01   36.5
2023-01-03   68.0
2023-01-05   29.0
2023-01-07   71.0
2023-01-09   36.0

### Interview Q: Shift vs Diff
**Q: What does `shift(1)` do?**
**A:** Moves data forward by 1 time unit.

**Q: What does `diff(1)` do?**
**A:** Computes the difference between current and previous values.

## 🚀 Interview-Level Exercises + Answers

In [21]:
# Q1. Compute 7-day rolling average of the `value` column.
ts_df['7D_avg'] = ts_df['value'].rolling(window=7).mean()
ts_df.head(10)

            value     7D_avg
date
2023-01-01     62        NaN
2023-01-02     11        NaN
2023-01-03     97        NaN
2023-01-04     39        NaN
2023-01-05     47        NaN
2023-01-06     11        NaN
2023-01-07     73  48.571429
2023-01-08     69  49.571429
2023-01-09     30  52.285714
2023-01-10     42  44.428571

In [23]:
# Q2. Create a MultiIndexed DataFrame from a CSV-style data.
sales = pd.DataFrame({
    'Region': ['East', 'East', 'West', 'West'],
    'Product': ['A', 'B', 'A', 'B'],
    'Sales': [200, 300, 400, 250]
}).set_index(['Region', 'Product'])
sales

                Sales
Region Product
East   A          200
       B          300
West   A          400
       B          250

**Q: How do you retrieve all sales for Product A?**
**A:** `sales.xs('A', level='Product')`